import { FileText, ShieldCheck, UploadCloud } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { VerificationResult } from '~/types/verification'
import { VerificationResultView } from './verification-result'

export function DocumentUpload() {
  const input=useRef<HTMLInputElement>(null)
  const [file,setFile]=useState<File>()
  const [drag,setDrag]=useState(false)
  const [busy,setBusy]=useState(false)
  const [stage,setStage]=useState('')
  const [result,setResult]=useState<VerificationResult>()
  const [error,setError]=useState('')
  const [previewUrl,setPreviewUrl]=useState('')
  useEffect(()=>{if(!file){setPreviewUrl('');return}const url=URL.createObjectURL(file);setPreviewUrl(url);return()=>URL.revokeObjectURL(url)},[file])
  const choose=(f?:File)=>{setError('');setResult(undefined);if(f)setFile(f)}
  async function verify(){if(!file)return;setBusy(true);setError('');setStage(file.type==='application/pdf'?'Reading every PDF page':'Reading image with OCR');const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),75_000);try{const body=new FormData();body.append('document',file);const response=await fetch('/api/verify-document',{method:'POST',body,signal:controller.signal});setStage('Checking policy dates and cover');const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error||`The server could not process the document (${response.status}).`);if(!data)throw new Error('The server returned an invalid response.');setResult(data)}catch(e){setError(e instanceof DOMException&&e.name==='AbortError'?'Document processing timed out. Try a smaller or clearer document.':e instanceof Error?e.message:'The document could not be processed.')}finally{window.clearTimeout(timeout);setBusy(false);setStage('')}}
  function reset(){setFile(undefined);setResult(undefined);setError('');if(input.current)input.current.value=''}
  if(result)return <VerificationResultView result={result} onReset={reset} previewUrl={previewUrl}/>
  return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_16px_60px_rgba(30,50,90,.08)] sm:p-9"><div onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0])}} className={`rounded-2xl border-2 border-dashed p-9 text-center transition ${drag?'border-blue-500 bg-blue-50':'border-slate-300 bg-slate-50'}`}><div className="mx-auto mb-4 grid size-14 place-items-center rounded-2xl bg-blue-100 text-blue-700"><UploadCloud/></div><h2 className="text-lg font-semibold">Upload an insurance certificate</h2><p className="mt-2 text-sm text-slate-500">Drag and drop one PDF, JPG or PNG here</p><input ref={input} type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" className="hidden" onChange={e=>choose(e.target.files?.[0])}/><button type="button" onClick={()=>input.current?.click()} className="mt-5 rounded-xl border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold shadow-sm hover:bg-slate-50">Choose document</button><p className="mt-3 text-xs text-slate-400">Maximum 4 MB · PDFs up to 20 pages</p></div>{file&&<div className="mt-5 flex items-center gap-3 rounded-xl border border-slate-200 p-4"><FileText className="text-blue-600"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{file.name}</p><p className="text-xs text-slate-500">{(file.size/1024/1024).toFixed(2)} MB</p></div>{previewUrl&&<a href={previewUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-blue-200 px-3 py-2 text-xs font-semibold text-blue-700 hover:bg-blue-50">View document</a>}</div>}{stage&&<div className="mt-5 flex items-center gap-3 rounded-xl bg-blue-50 p-4 text-sm text-blue-800"><span className="size-4 animate-spin rounded-full border-2 border-blue-200 border-t-blue-700"/>{stage}</div>}{error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<button onClick={verify} disabled={!file||busy} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-700 px-5 py-3.5 font-semibold text-white hover:bg-blue-800 disabled:bg-slate-300"><ShieldCheck size={19}/>{busy?'Verifying document…':'Verify document'}</button></div>
}
